version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/vrshow
permissions:
  - object: /home/ec2-user/vrshow
    owner: ec2-user
hooks:
  ApplicationStop:
    - location: bin/ApplicationStop.sh
      timeout: 180
  ApplicationStart:
    - location: bin/ApplicationStart.sh
      timeout: 180
  AfterInstall:
    - location: bin/AfterInstall.sh
      timeout: 180000
